### ISSUE TITLE
Cannot specify icon index - reads from stdin instead of argument string

### ISSUE THREAD

**Issue by starfishpatkhoo** [darealshinji/mkshortcut#1]
When using a command such as:

```
mkshortcut.exe /o:"Test.lnk" /t:"cmd.exe" /i:"%SystemRoot%\System32\shell32.dll" /n:244
```

Creating the link fails. I looked briefly at your code, especially line

https://github.com/darealshinji/mkshortcut/blob/4674058f19c092ac7317b80835c14e2c6289b1c7/mkshortcut.cpp#L356 

I think `_tscanf_s` should be `_stscanf_s` no?

I didn't test, but the same might be true of line

https://github.com/darealshinji/mkshortcut/blob/4674058f19c092ac7317b80835c14e2c6289b1c7/mkshortcut.cpp#L228

Otherwise, thank you very much for this simple but useful tool .. ^_^

**Comment by darealshinji** [comment]
Thanks. Indeed, I used the wrong `tchar` routine macro. It's working now.

**Comment by starfishpatkhoo** [comment]
Awesome! Works great! Thank you!

But by the way, `mkshortcut` with `/min` will set `SW_SHOWMINNOACTIVE` which I believe is the **correct thing to do**
https://github.com/darealshinji/mkshortcut/blob/57065f97423778e31ee89760413d4985d618eda6/mkshortcut.cpp#L323

But `shortcutinfo` only checks for `SW_SHOWMINIMIZED`
https://github.com/darealshinji/mkshortcut/blob/57065f97423778e31ee89760413d4985d618eda6/shortcutinfo.cpp#L198

So after creating the link with `/min`, using `shortcutinfo` on it will display `0x07 (not supported)` even though  `mkshortcut` did the right thing, and the shortcut works as expected.. So it's just a small display issue.. No biggie ^_^

**Comment by darealshinji** [comment]
Thanks again. Let me know if you find something else.

**Comment by starfishpatkhoo** [comment]
> Thanks again. Let me know if you find something else.

Looks good so far, I haven't noticed anything else ^_^

**Comment by starfishpatkhoo** [comment]
r4 Looks good, thanks again for the useful little tool ^_^
